import { Paragraph, Table } from 'docx'
import { describe, expect, it } from 'vitest'
import {
  degradeMathDelimiters,
  docxDocumentOptions,
  docxFileName,
  markdownToDocxBlocks,
} from './docxExport'

const AI_NOTICE = 'This text was generated by an AI system (Inqtrix).'

describe('degradeMathDelimiters', () => {
  it('unwraps block and bracketed math to source text', () => {
    expect(degradeMathDelimiters('$$E = mc^2$$')).toBe('E = mc^2')
    expect(degradeMathDelimiters('\\[a^2 + b^2\\]')).toBe('a^2 + b^2')
    expect(degradeMathDelimiters('\\(x_i\\)')).toBe('x_i')
  })

  it('unwraps inline math only when it looks like math', () => {
    expect(degradeMathDelimiters('Sei $x_i = 0$ gegeben.')).toBe('Sei x_i = 0 gegeben.')
    expect(degradeMathDelimiters('Das kostet $5 und $10.')).toBe('Das kostet $5 und $10.')
  })

  it('leaves plain text untouched', () => {
    expect(degradeMathDelimiters('Kein Mathe hier.')).toBe('Kein Mathe hier.')
  })
})

describe('docxFileName', () => {
  const at = new Date(2026, 5, 1, 9, 7, 5)

  it('slugifies a short title and appends a YYYYMMDD-HHMMSS stamp', () => {
    expect(docxFileName('Gemini als KI-Produktfamilie', at))
      .toBe('gemini-als-ki-produktfamilie-20260601-090705.docx')
  })

  it('caps the title slug at 40 characters before the stamp', () => {
    const longTitle = 'Ein sehr langer Dokumenttitel der deutlich ueber vierzig Zeichen hinausgeht'
    const name = docxFileName(longTitle, at)
    expect(name.endsWith('-20260601-090705.docx')).toBe(true)
    expect(name.replace('-20260601-090705.docx', '').length).toBeLessThanOrEqual(40)
  })

  it('folds diacritics and umlauts to ASCII', () => {
    expect(docxFileName('Übersicht über Ähnliches', at)).toBe('ubersicht-uber-ahnliches-20260601-090705.docx')
  })

  it('falls back when the title yields no usable characters', () => {
    expect(docxFileName('   ', at)).toBe('dokument-20260601-090705.docx')
    expect(docxFileName('***', at)).toBe('dokument-20260601-090705.docx')
  })
})

describe('markdownToDocxBlocks', () => {
  it('maps headings, paragraphs, lists, tables and code to docx blocks', () => {
    const markdown = [
      '# Titel',
      '',
      'Ein **fetter** Absatz mit [Link](https://example.com).',
      '',
      '- eins',
      '- zwei',
      '',
      '| A | B |',
      '| - | - |',
      '| 1 | 2 |',
      '',
      '```ts',
      'const x = 1',
      '```',
    ].join('\n')
    const blocks = markdownToDocxBlocks(markdown)
    expect(blocks.length).toBeGreaterThan(0)
    expect(blocks.some((block) => block instanceof Table)).toBe(true)
    expect(blocks.every((block) => block instanceof Paragraph || block instanceof Table)).toBe(true)
  })

  it('skips raw HTML nodes for safety', () => {
    const blocks = markdownToDocxBlocks('<script>alert(1)</script>\n\nText.')
    expect(blocks.every((block) => block instanceof Paragraph)).toBe(true)
    expect(blocks.length).toBe(1)
  })
})

describe('docxDocumentOptions', () => {
  it('marks a generated report in the core properties a reader can see', () => {
    const options = docxDocumentOptions('# Report\n\nBody.', 'Quarterly review', {
      notice: AI_NOTICE,
    })

    expect(options.creator).toBe('Inqtrix')
    expect(options.description).toBe(AI_NOTICE)
    expect(options.keywords).toContain('ai-generated')
    expect(options.lastModifiedBy).toBe('Inqtrix')
    expect(options.title).toBe('Quarterly review')
  })

  it('writes the machine-readable custom properties', () => {
    const options = docxDocumentOptions('Body.', 'T', { notice: AI_NOTICE })

    expect(options.customProperties).toEqual([
      { name: 'AIGenerated', value: 'true' },
      { name: 'AIProducer', value: 'Inqtrix' },
      { name: 'AIMarker', value: 'ai-generated' },
      { name: 'AIDisclosure', value: AI_NOTICE },
    ])
  })

  it('leaves a document the user wrote unmarked when no disclosure is given', () => {
    const options = docxDocumentOptions('Body.', 'My notes')

    expect(options.creator).toBeUndefined()
    expect(options.description).toBeUndefined()
    expect(options.keywords).toBeUndefined()
    expect(options.customProperties).toBeUndefined()
    expect(options.title).toBe('My notes')
  })

  it('builds a usable section either way', () => {
    for (const disclosure of [undefined, { notice: AI_NOTICE }]) {
      const options = docxDocumentOptions('# H\n\nBody.', 'T', disclosure)

      expect(options.sections).toHaveLength(1)
      expect(options.sections[0].children.length).toBeGreaterThan(0)
    }
  })
})
