import { Paragraph } from 'docx'
import { describe, expect, it } from 'vitest'
import { latexReportSection } from './latexReportStyle'

const NOTICE = 'This text was generated by an AI system (Inqtrix).'

/** The footer is the only place the AI marker survives a page being printed
 * or lifted out of the document, so it must not displace the page number. */
describe('latexReportSection footer', () => {
  it('carries only the page number when no notice is given', () => {
    const section = latexReportSection([new Paragraph({ text: 'Body.' })])

    expect(section.footers?.default?.options.children).toHaveLength(1)
  })

  it('adds the notice above the page number, keeping both', () => {
    const section = latexReportSection([new Paragraph({ text: 'Body.' })], NOTICE)
    const children = section.footers?.default?.options.children ?? []

    expect(children).toHaveLength(2)
    expect(JSON.stringify(children[0])).toContain(NOTICE)
  })

  it('ignores a blank notice rather than emitting an empty line', () => {
    const section = latexReportSection([new Paragraph({ text: 'Body.' })], '   ')

    expect(section.footers?.default?.options.children).toHaveLength(1)
  })
})
