"""Fake LLM and search providers for the offline end-to-end harness.

These fakes sit ONLY at the LLM / search I/O boundary. Every graph node,
strategy, consolidation step and contract computation runs the real
``inqtrix`` code; the fakes just feed deterministic provider outputs in.

Design goals:

* :class:`FakeSearch` replays a real captured ``GroundedSearchResult`` (the
  NVIDIA Quartalszahlen fixture) so the source/citation/rank shape that flows
  into the evidence pipeline is the production shape, not a hand-built stub.
* :class:`FakeLLM` is scenario-driven. It routes the four real prompt kinds
  (classify, plan, evaluate, answer) by marker text, and emits structured
  claim-extraction payloads + answer prose that the caller wires per test.
  The answer text is generated by reading the ``[E#]`` evidence labels out of
  the section prompt the real answer node hands it, so a "clean" scenario can
  cite exactly the labels the real graph assigned without the test hard-coding
  them.

The loader mirrors ``tests/fixtures/bedrock_responses.py``: fixtures live as
JSON under ``tests/fixtures/search_results/`` so the protective sanitization
scan discovers them automatically.
"""

from __future__ import annotations

import copy
import json
import pathlib
import re
import threading
from dataclasses import replace
from types import SimpleNamespace
from typing import Any, Sequence

from inqtrix.providers.base import LLMResponse, StructuredLLMResponse
from inqtrix.search_result import GroundedSearchResult, GroundedSource

_FIXTURE_ROOT = pathlib.Path(__file__).resolve().parent / "fixtures" / "search_results"

# Match the [E#] source labels the answer node embeds in the section prompt.
_EVIDENCE_LABEL_RE = re.compile(r"\[(E\d+)\]")


# --------------------------------------------------------------------------- #
# Fixture loader
# --------------------------------------------------------------------------- #


def load_search_result_fixture(slug: str) -> GroundedSearchResult:
    """Hydrate a :class:`GroundedSearchResult` from a captured JSON fixture.

    Args:
        slug: File stem under ``tests/fixtures/search_results/`` without the
            ``.json`` suffix (for example ``"nvidia_quartalszahlen"``). A
            missing file raises :class:`FileNotFoundError` with the resolved
            path so a typo in the test surfaces immediately.

    Returns:
        A :class:`GroundedSearchResult` whose sources preserve the captured
        ``rank`` ordinals — those are what the synthesized answer's inline
        ``[id]`` citations reference and what the claim extractor resolves
        ``provider_refs`` against.

    Notes:
        Top-level and per-source keys beginning with ``_`` (for example the
        ``_capture`` provenance note) are ignored so capture metadata never
        leaks into the typed result.
    """
    path = _FIXTURE_ROOT / f"{slug}.json"
    if not path.exists():
        raise FileNotFoundError(f"Search fixture {slug!r} not found at {path}")
    raw = json.loads(path.read_text(encoding="utf-8"))
    payload = {k: v for k, v in raw.items() if not k.startswith("_")}
    sources = [
        GroundedSource(
            **{k: v for k, v in source.items() if not k.startswith("_")}
        )
        for source in payload.get("sources", [])
    ]
    return GroundedSearchResult(
        answer=payload.get("answer", ""),
        sources=sources,
        related_questions=list(payload.get("related_questions", []) or []),
        prompt_tokens=int(payload.get("prompt_tokens", 0) or 0),
        completion_tokens=int(payload.get("completion_tokens", 0) or 0),
    )


def source_only_result(base: GroundedSearchResult) -> GroundedSearchResult:
    """Return *base* with the synthesized answer stripped but sources kept.

    Models a provider (e.g. a URL-only backend) that returns citable sources
    without prose. Claim extraction yields nothing without answer text, so the
    real graph must ingest these purely as source-context evidence records.
    """
    return GroundedSearchResult(
        answer="",
        sources=list(base.sources),
        related_questions=list(base.related_questions),
        prompt_tokens=base.prompt_tokens,
        completion_tokens=base.completion_tokens,
    )


def subset_result(
    base: GroundedSearchResult,
    ranks: Sequence[int],
    *,
    answer: str | None = None,
) -> GroundedSearchResult:
    """Carve a per-query result out of a captured fixture's real sources.

    Keeps only the sources whose original ``rank`` is in *ranks*, re-ranked
    1..N to mirror how each provider query independently ranks its own hits.
    Source content (real URLs/titles/snippets/dates from the capture) is left
    intact -- only the partition and the ordinal change -- so a multi-query
    scenario combines AUTHENTIC source shapes from distinct queries rather than
    invented stubs.

    Args:
        base: The loaded fixture to slice.
        ranks: Original 1-based ranks to keep, in the order they should appear.
        answer: Optional per-query answer text. ``None`` reuses the fixture's
            answer; pass a short query-specific answer when the inline-citation
            ordinals of the full fixture answer would not match the slice.

    Returns:
        A :class:`GroundedSearchResult` carrying the selected sources re-ranked
        from 1, suitable as one query's reply in :class:`FakeSearch`.
    """
    by_rank = {s.rank: s for s in base.sources}
    kept = [
        replace(by_rank[r], rank=i)
        for i, r in enumerate((r for r in ranks if r in by_rank), start=1)
    ]
    return GroundedSearchResult(
        answer=base.answer if answer is None else answer,
        sources=kept,
        related_questions=list(base.related_questions),
        prompt_tokens=base.prompt_tokens,
        completion_tokens=base.completion_tokens,
    )


# --------------------------------------------------------------------------- #
# FakeSearch
# --------------------------------------------------------------------------- #


class FakeSearch:
    """Replay canned :class:`GroundedSearchResult`(s) for the graph's queries.

    Each :meth:`search` call returns a deep copy so a node that mutates the
    result in place cannot poison later queries.

    Two modes:

    * Single result (``FakeSearch(result)``): every query gets the same reply
      -- the right shape for single-query scenarios.
    * Multiple results (``FakeSearch(results=[r1, r2, ...])``): replies are
      served round-robin across calls (thread-safe, since the search node runs
      queries in a ``ThreadPoolExecutor``). With N distinct results and N
      planned queries each query gets a different reply, so the Evidence Ledger
      genuinely COMBINES distinct per-query evidence (cross-query consolidation,
      signature-dedup, cross-checking across domains from different queries) --
      the multi-query case a single fixed reply cannot exercise. The assignment
      of which reply goes to which query is order-based and not asserted; only
      that distinct replies combine.
    """

    def __init__(
        self,
        result: GroundedSearchResult | None = None,
        *,
        results: Sequence[GroundedSearchResult] | None = None,
    ) -> None:
        """Bind the canned reply (single) or replies (round-robin) to serve.

        Args:
            result: Single reply returned for every query (back-compatible
                single-query mode). Mutually exclusive with *results*.
            results: Ordered replies served round-robin across :meth:`search`
                calls for multi-query combination scenarios.
        """
        if results is not None:
            self._results = list(results)
        elif result is not None:
            self._results = [result]
        else:
            self._results = [GroundedSearchResult()]
        self._lock = threading.Lock()
        self._call_index = 0

    def search(self, query: str, **kwargs: Any) -> GroundedSearchResult:
        """Return a deep copy of the next canned reply (round-robin)."""
        with self._lock:
            result = self._results[self._call_index % len(self._results)]
            self._call_index += 1
        return copy.deepcopy(result)

    def is_available(self) -> bool:
        """Report the fake as configured and ready."""
        return True

    @property
    def search_model(self) -> str:
        """Operator-facing identifier for the fake search backend."""
        return "fake-search"


# --------------------------------------------------------------------------- #
# FakeLLM
# --------------------------------------------------------------------------- #


class FakeLLM:
    """Scenario-driven fake LLM covering the surface the graph nodes use.

    Routing of :meth:`complete` is by marker text in the prompt, matching the
    real node prompts:

    * ``"KLASSIFIKATION"`` -> classify block (``DECISION: SEARCH`` etc.).
    * ``"CONFIDENCE:"`` -> evaluate block that ends the loop after one round.
    * otherwise -> the plan node, which expects a JSON array of query strings.

    :meth:`complete_structured` is the claim extractor's path; it returns the
    caller-supplied ``claims`` payload. :meth:`complete_with_metadata` is the
    answer node's per-section path; it returns scenario-specific markdown.

    The answer markdown is built from a small spec: the fake reads the ``[E#]``
    labels present in the section prompt and, for each requested binding, emits
    a sentence that cites that label and restates the claim text so the real
    binding heuristic (``_claim_plausible_in_segment``) can match it.
    """

    def __init__(
        self,
        *,
        classify_decision: str = "SEARCH",
        classify_language: str = "de",
        classify_search_language: str = "de",
        classify_recency: str = "NONE",
        classify_type: str = "GENERAL",
        sub_questions: list[str] | None = None,
        plan_queries: list[str] | None = None,
        evaluate_confidence: int = 8,
        evaluate_status: str = "SUFFICIENT",
        claim_payload: list[dict[str, Any]] | None = None,
        answer_bindings: list[dict[str, str]] | None = None,
        answer_extra_text: str = "",
        answer_override: str | None = None,
    ) -> None:
        """Wire one concrete scenario into the fake LLM.

        Args:
            classify_decision: ``SEARCH`` (research) or ``DIRECT`` (skip
                search). The harness scenarios always research.
            classify_language / classify_search_language: ISO codes echoed in
                the classify block.
            classify_recency: One of ``NONE/HOUR/DAY/WEEK/MONTH``.
            classify_type: One of ``GENERAL/ACADEMIC/NEWS``.
            sub_questions: Decomposed sub-questions; defaults to a single
                generic one so the focus-stem filter stays permissive.
            plan_queries: Query strings the plan node should emit as a JSON
                array. Defaults to two NVIDIA-relevant queries.
            evaluate_confidence: CONFIDENCE value (1-10) for the evaluate
                block. ``8`` matches the default ``confidence_stop``.
            evaluate_status: STATUS token (``SUFFICIENT``/``INSUFFICIENT``).
            claim_payload: The ``claims`` list returned by
                :meth:`complete_structured`. ``None`` -> no claims (an empty
                list), which models a valid-empty extraction.
            answer_bindings: List of ``{"label": "E#", "claim_text": "..."}``
                hints. For each, the answer prose emits one sentence citing
                ``[E#]`` and restating ``claim_text`` so a claim that shares
                that source URL binds as ``matched``. The fake auto-rewrites a
                requested label to one actually present in the prompt when the
                exact label is absent.
            answer_extra_text: Extra prose appended to every section body.
            answer_override: When set, every section returns this exact markdown
                verbatim, ignoring bindings/labels. Models an LLM that writes
                arbitrary prose -- e.g. citation-free body text -- so a scenario
                can exercise an answer that ignores the available evidence.
        """
        self.models = SimpleNamespace(
            reasoning_model="reasoning-model",
            effective_classify_model="classify-model",
            effective_evaluate_model="evaluate-model",
            effective_claim_extract_model="claim-extract-model",
        )
        self._classify_decision = classify_decision
        self._classify_language = classify_language
        self._classify_search_language = classify_search_language
        self._classify_recency = classify_recency
        self._classify_type = classify_type
        self._sub_questions = sub_questions or ["NVIDIA Quartalszahlen"]
        self._plan_queries = plan_queries or [
            "Welche Quartalszahlen hat NVIDIA zuletzt gemeldet?",
            "Wie hoch war der NVIDIA Umsatz im ersten Quartal Geschaeftsjahr 2027?",
        ]
        self._evaluate_confidence = int(evaluate_confidence)
        self._evaluate_status = evaluate_status
        self._claim_payload = claim_payload if claim_payload is not None else []
        self._answer_bindings = answer_bindings or []
        self._answer_extra_text = answer_extra_text
        self._answer_override = answer_override

        # Diagnostics the tests can read to confirm routing happened through
        # the real nodes rather than a fake short-circuit.
        self.complete_calls: list[str] = []
        self.structured_calls = 0
        self.answer_section_calls = 0

    # -- capability flags ------------------------------------------------- #
    def is_available(self) -> bool:
        """Report the fake as configured and ready."""
        return True

    def supports_structured_output(self, *, model: str | None = None) -> bool:
        """Advertise native structured output so the claim extractor uses it."""
        return True

    # -- routing helpers -------------------------------------------------- #
    def _classify_block(self) -> str:
        return (
            f"DECISION: {self._classify_decision}\n"
            f"LANGUAGE: {self._classify_language}\n"
            f"SEARCH_LANGUAGE: {self._classify_search_language}\n"
            f"RECENCY: {self._classify_recency}\n"
            f"TYPE: {self._classify_type}\n"
            f"SUB_QUESTIONS: {json.dumps(self._sub_questions, ensure_ascii=False)}"
        )

    def _evaluate_block(self) -> str:
        return (
            f"STATUS: {self._evaluate_status}\n"
            f"CONFIDENCE: {self._evaluate_confidence}\n"
            "GAPS: Keine\n"
            "CONTRADICTIONS: Nein\n"
            "COMPETING_EVENTS: Keine\n"
            "EVIDENCE_CONSISTENCY: 9\n"
            "EVIDENCE_SUFFICIENCY: 9"
        )

    def _plan_block(self) -> str:
        return json.dumps(self._plan_queries, ensure_ascii=False)

    # -- LLMProvider surface ---------------------------------------------- #
    def complete(self, prompt: str, **kwargs: Any) -> str:
        """Route a reasoning call by marker text to classify/evaluate/plan."""
        if "KLASSIFIKATION" in prompt:
            self.complete_calls.append("classify")
            return self._classify_block()
        if "CONFIDENCE:" in prompt:
            self.complete_calls.append("evaluate")
            return self._evaluate_block()
        self.complete_calls.append("plan")
        return self._plan_block()

    def complete_with_metadata(self, prompt: str, **kwargs: Any) -> LLMResponse:
        """Answer-node path: synthesize scenario markdown for one section.

        The answer node calls this once per report section with the section
        system prompt embedded under ``system=`` and the section task under
        ``prompt=``. The evidence overview (with ``[E#]`` labels) lives in the
        system prompt, so the fake reads labels from BOTH the prompt and the
        system text, then emits binding sentences for the configured labels.
        """
        self.answer_section_calls += 1
        system = str(kwargs.get("system", "") or "")
        available_labels = _EVIDENCE_LABEL_RE.findall(f"{system}\n{prompt}")
        body = self._build_answer_body(available_labels)
        return LLMResponse(
            content=body,
            model="reasoning-model",
            finish_reason="stop",
        )

    def complete_structured(
        self,
        prompt: str,
        *,
        schema: dict[str, Any],
        schema_name: str,
        **kwargs: Any,
    ) -> StructuredLLMResponse:
        """Claim-extractor path: return the scenario's ``claims`` payload."""
        self.structured_calls += 1
        return StructuredLLMResponse(
            parsed={"claims": copy.deepcopy(self._claim_payload)},
            content="",
            model="claim-extract-model",
            finish_reason="stop",
            schema_name=schema_name,
        )

    # -- answer synthesis ------------------------------------------------- #
    def _build_answer_body(self, available_labels: list[str]) -> str:
        """Compose section markdown citing configured ``[E#]`` labels.

        For each requested binding, emit one sentence that cites the label and
        restates the claim text. When the requested label is not present in the
        prompt (label assignment is score-dependent and the test cannot predict
        it), fall back to the first available label so the citation is still on
        the allow-list and resolves to a real source.

        When ``answer_override`` was supplied, return it verbatim instead --
        modelling an LLM that writes arbitrary prose (e.g. citation-free body).
        """
        if self._answer_override is not None:
            return self._answer_override

        ordered_unique: list[str] = []
        for label in available_labels:
            if label not in ordered_unique:
                ordered_unique.append(label)

        lines: list[str] = ["## Antwort", ""]
        used_fallback_index = 0
        for binding in self._answer_bindings:
            label = str(binding.get("label", "")).strip()
            claim_text = str(binding.get("claim_text", "")).strip()
            if label not in ordered_unique and ordered_unique:
                label = ordered_unique[used_fallback_index % len(ordered_unique)]
                used_fallback_index += 1
            if not label:
                continue
            # Restating the claim text inside the same sentence as the [E#]
            # citation is what makes the real claim/segment binding `matched`.
            lines.append(f"Laut [{label}] gilt: {claim_text}".rstrip())
            lines.append("")

        if self._answer_extra_text:
            lines.append(self._answer_extra_text)
            lines.append("")

        if len(lines) <= 2:
            # No bindings configured (source-only / source-context scenarios):
            # still produce a short, source-citing body when labels exist so
            # the URL-level audit has something to resolve.
            if ordered_unique:
                lines.append(
                    f"Die vorliegenden Quellen behandeln das Thema [{ordered_unique[0]}]."
                )
            else:
                lines.append(
                    "Zu dieser Frage liegen derzeit keine belegfaehigen Quellen vor."
                )
            lines.append("")

        return "\n".join(lines).rstrip() + "\n"
