""" Static default constants for agent behavior."""

from __future__ import annotations

MAX_ROUNDS = 4
CONFIDENCE_STOP = 8
FIRST_ROUND_QUERIES = 6
ANSWER_PROMPT_CITATIONS_MAX = 60

# Token capacity defaults
DEFAULT_LLM_MAX_OUTPUT_TOKENS = 64_000
REQUIRED_CONTEXT_WINDOW_TOKENS = 128_000
CONTEXT_WINDOW_SAFETY_TOKENS = 2_048

# Timeouts (seconds)
REASONING_TIMEOUT = 600
EDITOR_ASSISTANT_TIMEOUT = 600
SEARCH_TIMEOUT = 600
CLAIM_EXTRACT_TIMEOUT = 600
MAX_TOTAL_SECONDS = 3_600
REQUEST_WAIT_MARGIN_SECONDS = 30
"""Grace between an inner AI deadline and its outer client wait."""

MAX_QUESTION_LENGTH = 10_000

# Search cache defaults
SEARCH_CACHE_MAXSIZE = 256
SEARCH_CACHE_TTL = 3600

# Risk scoring
HIGH_RISK_SCORE_THRESHOLD = 4
