"""Project licensing and AI-transparency metadata for public discovery surfaces."""

PROJECT_NAME = "Inqtrix"
PROJECT_SOURCE_URL = "https://github.com/BZandi/inqtrix"
LICENSE_ID = "AGPL-3.0-only"
COPYRIGHT_NOTICE = "Copyright (c) 2026 Babak Zandi."
ATTRIBUTION_NOTICE = (
    "Inqtrix - Copyright (c) 2026 Babak Zandi - "
    "https://github.com/BZandi/inqtrix"
)
WARRANTY_NOTICE = (
    "This software is provided without warranty under AGPL-3.0-only; "
    "see LICENSE for details."
)

AI_SYSTEM_MARKER = "ai-generated"
AI_SYSTEM_PRODUCER = PROJECT_NAME
AI_SYSTEM_DISCLOSURE = (
    "Inqtrix is an AI system. Answers, reports, and suggestions are "
    "generated by language models."
)
AI_CONTENT_DISCLOSURE = "This text was generated by an AI system (Inqtrix)."


def legal_metadata() -> dict[str, str]:
    """Return stable project legal metadata for public discovery endpoints.

    The HTTP server exposes this payload on ``/health`` so network users
    can find the project source, active license identifier, copyright
    notice, and attribution notice without first locating repository docs.
    These values describe the project itself, so they are intentionally
    independent from the active provider stack.
    """
    return {
        "project": PROJECT_NAME,
        "license": LICENSE_ID,
        "source_url": PROJECT_SOURCE_URL,
        "copyright": COPYRIGHT_NOTICE,
        "notice": ATTRIBUTION_NOTICE,
        "warranty_notice": WARRANTY_NOTICE,
    }


def ai_disclosure_metadata() -> dict[str, str]:
    """Return the AI-transparency metadata for public discovery endpoints.

    The HTTP server exposes this payload on ``/health`` beside ``legal`` so
    an operator, an archiving tool, or a downstream client can identify the
    producer of generated text without scraping the user interface. It is a
    sibling of :func:`legal_metadata` rather than part of it: licensing and
    AI transparency answer different questions and change independently, and
    the ``legal`` block is pinned by contract tests as a whole.

    ``marker`` and ``producer`` are locale-neutral machine tokens and are the
    same values the browser writes into ``data-ai-generated`` /
    ``data-ai-producer`` and into exported document properties, so a consumer
    can match app output against the endpoint. The two disclosure sentences
    are English by repository convention; user-facing surfaces render their
    own localized wording instead of these strings.
    """
    return {
        "marker": AI_SYSTEM_MARKER,
        "producer": AI_SYSTEM_PRODUCER,
        "system_disclosure": AI_SYSTEM_DISCLOSURE,
        "content_disclosure": AI_CONTENT_DISCLOSURE,
    }
