/** Markers that identify model-generated text as such.
 *
 * Defined once so the DOM attributes, the clipboard, the Markdown front
 * matter, and the Word document properties all carry the same tokens
 * (Designprinzip 4). The tokens mirror the server's `/health`
 * `ai_disclosure` block, so a consumer can match app output against the
 * endpoint; the visible sentence is always passed in by the caller from
 * `t.aiTransparency.*`, because the server strings are English-only.
 *
 * Whole answers are marked, fragments are not: a table's source, a code
 * block, and a text selection stay byte-exact so a copy remains usable for
 * what it was copied for. */

/** Machine token written into `data-ai-generated` and into the exported
 * `AIMarker` document property. Locale-neutral by design. */
export const AI_GENERATED_MARKER = 'ai-generated'

/** Producing system, written into `data-ai-producer` and `AIProducer`. */
export const AI_PRODUCER = 'Inqtrix'

/** Locale-neutral disclosure for machine-facing files that have no locale in
 * scope — project files, whose front matter must stay byte-stable so that
 * re-exporting a project after a language switch produces no diff noise. It
 * matches the server's `ai_disclosure.content_disclosure`. Surfaces a person
 * reads use the localized `t.aiTransparency.exportNotice` instead. */
export const AI_CONTENT_DISCLOSURE = 'This text was generated by an AI system (Inqtrix).'

/** Append `notice` to generated Markdown as a trailing blockquote.
 *
 * A blockquote reads as an annotation rather than as another paragraph of
 * the answer, which matters because the result is often pasted straight
 * into a document. Idempotent: text that already ends with this exact
 * notice is returned unchanged, so an export of an already-marked copy
 * does not stack duplicates. Empty or blank input is returned as-is —
 * there is nothing to disclose about an empty string. */
export function withAiDisclosure(markdown: string, notice: string): string {
  if (!markdown.trim() || !notice.trim()) return markdown
  const marker = `> ${notice.trim()}`
  const body = markdown.trimEnd()
  if (body.endsWith(marker)) return markdown
  return `${body}\n\n${marker}\n`
}

/** Front-matter keys that travel with exported Markdown.
 *
 * These belong in the front matter and never in the body: the project
 * importer assigns the parsed body straight back to the answer text, so a
 * body marker would be absorbed into the answer and duplicated on every
 * export/import round trip. */
export function aiDisclosureFrontmatter(notice: string): Record<string, unknown> {
  return {
    ai_generated: true,
    ai_producer: AI_PRODUCER,
    ai_marker: AI_GENERATED_MARKER,
    ai_disclosure: notice,
  }
}

/** Document properties for the Word export.
 *
 * `core` lands in `docProps/core.xml` (Word's Info pane, Explorer, indexing
 * tools); `custom` lands in `docProps/custom.xml` and is the actual
 * machine-readable channel. Kept here rather than in the export module so
 * the tokens have one definition. */
export function aiDisclosureDocumentProperties(notice: string, model?: string) {
  const custom = [
    { name: 'AIGenerated', value: 'true' },
    { name: 'AIProducer', value: AI_PRODUCER },
    { name: 'AIMarker', value: AI_GENERATED_MARKER },
    { name: 'AIDisclosure', value: notice },
  ]
  if (model) custom.push({ name: 'AIModel', value: model })
  return {
    core: {
      creator: AI_PRODUCER,
      description: notice,
      keywords: `${AI_GENERATED_MARKER}; ${AI_PRODUCER}`,
      lastModifiedBy: AI_PRODUCER,
    },
    custom,
  }
}
