import { describe, expect, it } from 'vitest'

import {
  AI_GENERATED_MARKER,
  AI_PRODUCER,
  aiDisclosureDocumentProperties,
  aiDisclosureFrontmatter,
  withAiDisclosure,
} from './aiDisclosure'

const NOTICE = 'This text was generated by an AI system (Inqtrix).'

describe('withAiDisclosure', () => {
  it('appends the notice as a trailing blockquote', () => {
    expect(withAiDisclosure('Answer body.', NOTICE)).toBe(
      `Answer body.\n\n> ${NOTICE}\n`,
    )
  })

  it('does not stack duplicates when the text is already marked', () => {
    const once = withAiDisclosure('Answer body.', NOTICE)

    expect(withAiDisclosure(once, NOTICE)).toBe(once)
  })

  it('leaves empty or blank input untouched', () => {
    expect(withAiDisclosure('', NOTICE)).toBe('')
    expect(withAiDisclosure('   ', NOTICE)).toBe('   ')
  })

  it('leaves the text untouched when there is no notice to add', () => {
    expect(withAiDisclosure('Answer body.', '')).toBe('Answer body.')
  })

  it('normalises trailing whitespace before appending', () => {
    expect(withAiDisclosure('Answer body.\n\n\n', NOTICE)).toBe(
      `Answer body.\n\n> ${NOTICE}\n`,
    )
  })
})

describe('aiDisclosureFrontmatter', () => {
  it('carries the machine tokens and the visible notice', () => {
    expect(aiDisclosureFrontmatter(NOTICE)).toEqual({
      ai_generated: true,
      ai_producer: AI_PRODUCER,
      ai_marker: AI_GENERATED_MARKER,
      ai_disclosure: NOTICE,
    })
  })
})

describe('aiDisclosureDocumentProperties', () => {
  it('fills the core properties a reader sees in Word and Explorer', () => {
    const { core } = aiDisclosureDocumentProperties(NOTICE)

    expect(core.creator).toBe(AI_PRODUCER)
    expect(core.description).toBe(NOTICE)
    expect(core.keywords).toContain(AI_GENERATED_MARKER)
  })

  it('emits the machine-readable custom properties', () => {
    const { custom } = aiDisclosureDocumentProperties(NOTICE)

    expect(custom).toEqual([
      { name: 'AIGenerated', value: 'true' },
      { name: 'AIProducer', value: AI_PRODUCER },
      { name: 'AIMarker', value: AI_GENERATED_MARKER },
      { name: 'AIDisclosure', value: NOTICE },
    ])
  })

  it('adds the model only when one is known', () => {
    const { custom } = aiDisclosureDocumentProperties(NOTICE, 'claude-opus-5')

    expect(custom).toContainEqual({ name: 'AIModel', value: 'claude-opus-5' })
  })
})
