/**
 * Localized UI copy for the editor feature (DE + EN), shared by the editor
 * shell (`EditorWorkspace`), the markdown surface
 * (`core/MarkdownEditorSurface`) and the diff view (`DocumentDiffView`) so all
 * editor strings stay in one place.
 */

export type EditorCopy = { [Key in keyof typeof editorCopy.de]: string }

export const editorCopy = {
  de: {
    exportWord: 'Als Word exportieren',
    exportWordFailed: 'Word-Export fehlgeschlagen',
    assistant: 'Editor-Assistent',
    assistantPlaceholder: 'Beschreiben Sie, was am Dokument geändert werden soll...',
    attachComments: 'Kommentare anhängen',
    attachedComments: 'Kommentare angehängt',
    assistantDone: 'Antwort',
    assistantThinking: 'Denke nach',
    documentChanges: 'Dokument-Änderungen',
    setDiffAnchor: 'Vergleichsanker setzen',
    showDiff: 'Diff-Ansicht einschalten',
    hideDiff: 'Diff-Ansicht ausschalten',
    diffView: 'Diff-Ansicht',
    noDiffAnchor: 'Setzen Sie zuerst einen Vergleichsanker.',
    acceptAll: 'Alle übernehmen',
    rejectAll: 'Alle verwerfen',
    noDocumentChanges: 'Noch keine Dokument-Änderungen.',
    refineSuggestion: 'Vorschlag verfeinern',
    editSuggestion: 'Vorschlag bearbeiten',
    saveSuggestion: 'Speichern',
    cancelEdit: 'Abbrechen',
    sendRefinement: 'Senden',
    refinementPlaceholder: 'Was soll am Vorschlag geändert werden?',
    refiningSuggestion: 'Überarbeite Vorschlag …',
    revision: 'Revision',
    removeFromQueue: 'Aus Warteschlange entfernen',
    removeFormatting: 'Formatierung entfernen',
    placeholderEmpty: 'Schreibe, oder tippe / für Befehle …',
    placeholderHeading: 'Überschrift',
    slashTitle: 'Befehle',
    slashEmpty: 'Keine Treffer',
    slashNav: 'Navigieren',
    slashSelect: 'Auswählen',
    slashClose: 'Schließen',
    slashGroupStyle: 'Stil',
    slashGroupInsert: 'Einfügen',
    slashText: 'Text',
    slashHeading1: 'Überschrift 1',
    slashHeading2: 'Überschrift 2',
    slashHeading3: 'Überschrift 3',
    slashBulletList: 'Aufzählung',
    slashOrderedList: 'Nummerierte Liste',
    slashTaskList: 'Aufgabenliste',
    slashBlockquote: 'Zitat',
    slashCodeBlock: 'Codeblock',
    bubbleComment: 'Kommentar',
    bubbleBold: 'Fett',
    bubbleItalic: 'Kursiv',
    bubbleUnderline: 'Unterstrichen',
    bubbleStrike: 'Durchgestrichen',
    bubbleCode: 'Code',
    bubbleHighlight: 'Hervorheben',
    slashTable: 'Tabelle',
    slashDivider: 'Trenner',
    blockHandleAria: 'Block-Optionen',
    blockTurnInto: 'Umwandeln in',
    blockDuplicate: 'Block duplizieren',
    blockDelete: 'Block löschen',
    blockMoveUp: 'Nach oben verschieben',
    blockMoveDown: 'Nach unten verschieben',
    tableColumnOptions: 'Spalten-Optionen',
    tableRowOptions: 'Zeilen-Optionen',
    tableColInsertLeft: 'Spalte links einfügen',
    tableColInsertRight: 'Spalte rechts einfügen',
    tableColMoveLeft: 'Spalte nach links',
    tableColMoveRight: 'Spalte nach rechts',
    tableSortAsc: 'Sortieren A–Z',
    tableSortDesc: 'Sortieren Z–A',
    tableColDuplicate: 'Spalte duplizieren',
    tableColClear: 'Spalteninhalt leeren',
    tableToggleHeaderRow: 'Kopfzeile umschalten',
    tableRowInsertAbove: 'Zeile oben einfügen',
    tableRowInsertBelow: 'Zeile unten einfügen',
    tableRowMoveUp: 'Zeile nach oben',
    tableRowMoveDown: 'Zeile nach unten',
    tableRowDuplicate: 'Zeile duplizieren',
    templates: 'Vorlagen',
    runSuggestion: 'Vorschlag erzeugen',
    runningSuggestion: 'Wird erzeugt …',
    accept: 'Übernehmen',
    reject: 'Verwerfen',
    proposedChange: 'Vorgeschlagene Änderung',
    proposedText: 'Vorschlag',
    warnings: 'Hinweise',
    changeSummary: 'Änderungen',
    reviewInEditor: 'Im Dokument übernehmen oder verwerfen',
    reviewInPanel: 'In der Karte übernehmen oder verwerfen',
    sources: 'Quellen',
    suggestionStale: 'Textstelle hat sich geändert. Bitte Vorschlag neu erzeugen.',
    regenerate: 'Neu erzeugen',
    changeKind: 'Typ ändern',
    comments: 'Kommentare',
    filterAll: 'Alle',
    kindCollect: 'Sammeln',
    kindEvidence: 'Beleg',
    kindInline: 'Direkt',
    preset: 'Preset',
    presetAddSources: 'Quellen ergänzen',
    presetFactCheck: 'Fakten prüfen',
    presetVerifyCitations: 'Zitate prüfen',
    reopen: 'Wieder öffnen',
    tabOpen: 'Offen',
    tabResolved: 'Erledigt',
    createDocument: 'Neue Datei',
    cancel: 'Abbrechen',
    createFolder: 'Neuer Ordner',
    deleteComment: 'Kommentar löschen',
    deleteDocument: 'Dokument löschen',
    editComment: 'Kommentar bearbeiten',
    save: 'Speichern',
    deleteFolder: 'Ordner löschen',
    documents: 'Dokumente',
    dropIntoFolder: 'In Ordner verschieben',
    emptyBody: 'Arbeitsfläche für Markdown, importierte Research Reports und KI-gestützte Überarbeitung.',
    emptyGuidance: 'Starten Sie mit einer leeren Datei zum Schreiben oder importieren Sie einen abgeschlossenen Research Report, um daraus ein bearbeitbares Dokument zu machen.',
    emptyExample: 'Der Editor-Assistent unterstützt beim Umformulieren, Prüfen von Aussagen und Arbeiten mit Kommentaren.',
    emptyKicker: 'Editor',
    emptyTitle: 'Kein Dokument geöffnet',
    focus: 'Fokus',
    hideAssistant: 'Editor-Assistent ausblenden',
    hideComments: 'Kommentare ausblenden',
    hideTree: 'Dateibaum ausblenden',
    resizeComments: 'Kommentarbreite anpassen',
    resizeTree: 'Dateibaumbreite anpassen',
    importReport: 'Research Report importieren',
    importedFrom: 'Importiert aus Research-Run',
    importedFromAgent: 'Übernommen aus Agent-Lauf',
    inlineComment: 'Kommentar hinzufügen...',
    inlineCommentSubmit: 'Kommentar',
    addColumn: 'Spalte hinzufügen',
    addRow: 'Zeile hinzufügen',
    closeTableEditor: 'Tabelleneditor schließen',
    columnLabel: 'Spalte',
    deleteColumn: 'Spalte löschen',
    deleteRow: 'Zeile löschen',
    formatTables: 'Markdown-Tabellen bereinigen',
    insertOrEditTable: 'Tabelle einfügen oder bearbeiten',
    sourceEditor: 'Markdown Source',
    sourceLineWrap: 'Zeilenumbruch umschalten',
    tableAlignmentCenter: 'Spalte zentrieren',
    tableAlignmentLeft: 'Spalte linksbündig ausrichten',
    tableAlignmentRight: 'Spalte rechtsbündig ausrichten',
    tableColumn: 'Spalten',
    tableEditor: 'Tabelleneditor',
    tableLines: 'Zeilen',
    tableRows: 'Datenzeilen',
    live: 'Live',
    markdown: 'Markdown',
    noComments: 'Noch keine Kommentare in diesem Dokument.',
    noDocuments: 'Noch keine Dokumente.',
    noReports: 'Keine abgeschlossenen Reports verfügbar.',
    options: 'Optionen',
    searchDocuments: 'Dokumente suchen',
    searchClear: 'Suche zurücksetzen',
    searchNoResults: 'Keine passenden Dokumente.',
    moveDocument: 'Dokument verschieben',
    moveFolder: 'Ordner verschieben',
    pinned: 'Angeheftet',
    pinDocument: 'Dokument anheften',
    renameDocument: 'Dokument umbenennen',
    renameFolder: 'Ordner umbenennen',
    resolve: 'Erledigen',
    send: 'Senden',
    showAssistant: 'Editor-Assistent einblenden',
    showComments: 'Kommentare einblenden',
    showLess: 'Weniger anzeigen',
    showMore: 'Mehr anzeigen',
    showTree: 'Dateibaum einblenden',
    source: 'Source',
    stopRun: 'Lauf abbrechen',
    unpinDocument: 'Dokument lösen',
    updated: 'zuletzt bearbeitet',
  },
  en: {
    exportWord: 'Export to Word',
    exportWordFailed: 'Word export failed',
    assistant: 'Editor assistant',
    assistantPlaceholder: 'Describe what should change in this document...',
    attachComments: 'Attach comments',
    attachedComments: 'comments attached',
    assistantDone: 'Response',
    assistantThinking: 'Thinking',
    documentChanges: 'Document changes',
    setDiffAnchor: 'Set comparison anchor',
    showDiff: 'Show diff view',
    hideDiff: 'Hide diff view',
    diffView: 'Diff view',
    noDiffAnchor: 'Set a comparison anchor first.',
    acceptAll: 'Accept all',
    rejectAll: 'Reject all',
    noDocumentChanges: 'No document changes yet.',
    refineSuggestion: 'Refine suggestion',
    editSuggestion: 'Edit suggestion',
    saveSuggestion: 'Save',
    cancelEdit: 'Cancel',
    sendRefinement: 'Send',
    refinementPlaceholder: 'What should change in this suggestion?',
    refiningSuggestion: 'Refining suggestion …',
    revision: 'Revision',
    removeFromQueue: 'Remove from queue',
    removeFormatting: 'Remove formatting',
    placeholderEmpty: 'Write, or type / for commands …',
    placeholderHeading: 'Heading',
    slashTitle: 'Commands',
    slashEmpty: 'No matches',
    slashNav: 'Navigate',
    slashSelect: 'Select',
    slashClose: 'Close',
    slashGroupStyle: 'Style',
    slashGroupInsert: 'Insert',
    slashText: 'Text',
    slashHeading1: 'Heading 1',
    slashHeading2: 'Heading 2',
    slashHeading3: 'Heading 3',
    slashBulletList: 'Bullet list',
    slashOrderedList: 'Numbered list',
    slashTaskList: 'To-do list',
    slashBlockquote: 'Quote',
    slashCodeBlock: 'Code block',
    bubbleComment: 'Comment',
    bubbleBold: 'Bold',
    bubbleItalic: 'Italic',
    bubbleUnderline: 'Underline',
    bubbleStrike: 'Strikethrough',
    bubbleCode: 'Code',
    bubbleHighlight: 'Highlight',
    slashTable: 'Table',
    slashDivider: 'Divider',
    blockHandleAria: 'Block options',
    blockTurnInto: 'Turn into',
    blockDuplicate: 'Duplicate block',
    blockDelete: 'Delete block',
    blockMoveUp: 'Move up',
    blockMoveDown: 'Move down',
    tableColumnOptions: 'Column options',
    tableRowOptions: 'Row options',
    tableColInsertLeft: 'Insert column left',
    tableColInsertRight: 'Insert column right',
    tableColMoveLeft: 'Move column left',
    tableColMoveRight: 'Move column right',
    tableSortAsc: 'Sort A–Z',
    tableSortDesc: 'Sort Z–A',
    tableColDuplicate: 'Duplicate column',
    tableColClear: 'Clear column contents',
    tableToggleHeaderRow: 'Toggle header row',
    tableRowInsertAbove: 'Insert row above',
    tableRowInsertBelow: 'Insert row below',
    tableRowMoveUp: 'Move row up',
    tableRowMoveDown: 'Move row down',
    tableRowDuplicate: 'Duplicate row',
    templates: 'Templates',
    runSuggestion: 'Generate suggestion',
    runningSuggestion: 'Generating …',
    accept: 'Accept',
    reject: 'Reject',
    proposedChange: 'Proposed change',
    proposedText: 'Suggestion',
    warnings: 'Warnings',
    changeSummary: 'Changes',
    reviewInEditor: 'Accept or reject it in the document',
    reviewInPanel: 'Accept or reject it in this card',
    sources: 'Sources',
    suggestionStale: 'The passage changed. Please regenerate the suggestion.',
    regenerate: 'Regenerate',
    changeKind: 'Change type',
    comments: 'Comments',
    filterAll: 'All',
    kindCollect: 'Collect',
    kindEvidence: 'Evidence',
    kindInline: 'Direct',
    preset: 'Preset',
    presetAddSources: 'Add sources',
    presetFactCheck: 'Fact-check',
    presetVerifyCitations: 'Verify citations',
    reopen: 'Reopen',
    tabOpen: 'Open',
    tabResolved: 'Resolved',
    createDocument: 'New file',
    cancel: 'Cancel',
    createFolder: 'New folder',
    deleteComment: 'Delete comment',
    deleteDocument: 'Delete document',
    editComment: 'Edit comment',
    save: 'Save',
    deleteFolder: 'Delete folder',
    documents: 'Documents',
    dropIntoFolder: 'Move into folder',
    emptyBody: 'Workspace for Markdown, imported research reports, and AI-assisted revision.',
    emptyGuidance: 'Start with a blank file for writing, or import a completed research report to turn it into an editable document.',
    emptyExample: 'The editor assistant helps rewrite passages, check claims, and work through comments.',
    emptyKicker: 'Editor',
    emptyTitle: 'No document open',
    focus: 'Focus',
    hideAssistant: 'Hide editor assistant',
    hideComments: 'Hide comments',
    hideTree: 'Hide file tree',
    resizeComments: 'Resize comments panel',
    resizeTree: 'Resize file tree',
    importReport: 'Import research report',
    importedFrom: 'Imported from research run',
    importedFromAgent: 'Brought in from agent run',
    inlineComment: 'Add comment...',
    inlineCommentSubmit: 'Comment',
    addColumn: 'Add column',
    addRow: 'Add row',
    closeTableEditor: 'Close table editor',
    columnLabel: 'Column',
    deleteColumn: 'Delete column',
    deleteRow: 'Delete row',
    formatTables: 'Clean up Markdown tables',
    insertOrEditTable: 'Insert or edit table',
    sourceEditor: 'Markdown source',
    sourceLineWrap: 'Toggle line wrap',
    tableAlignmentCenter: 'Center column',
    tableAlignmentLeft: 'Align column left',
    tableAlignmentRight: 'Align column right',
    tableColumn: 'Columns',
    tableEditor: 'Table editor',
    tableLines: 'Lines',
    tableRows: 'Data rows',
    live: 'Live',
    markdown: 'Markdown',
    noComments: 'No comments in this document yet.',
    noDocuments: 'No documents yet.',
    noReports: 'No completed reports available.',
    options: 'Options',
    searchDocuments: 'Search documents',
    searchClear: 'Clear search',
    searchNoResults: 'No matching documents.',
    moveDocument: 'Move document',
    moveFolder: 'Move folder',
    pinned: 'Pinned',
    pinDocument: 'Pin document',
    renameDocument: 'Rename document',
    renameFolder: 'Rename folder',
    resolve: 'Resolve',
    send: 'Send',
    showAssistant: 'Show editor assistant',
    showComments: 'Show comments',
    showLess: 'Show less',
    showMore: 'Show more',
    showTree: 'Show file tree',
    source: 'Source',
    stopRun: 'Cancel run',
    unpinDocument: 'Unpin document',
    updated: 'last edited',
  },
} as const
